eclipse-tractusx/portal-iam

.github/workflows/trivy.yml
fix trivy: don't fail on high findings
action should only fail if there is an error/misconfiguration
relates to https://github.com/eclipse-tractusx/portal-frontend/pull/353
=> fix(trivy): don't fail on high findings

charts/centralidp/templates/job-seeding.yaml, charts/centralidp/values.yaml
Add configuration to exclude bpn and organisation from user attributes while seeding
To not overwrite already existing values
N/A - Jira Issue: CPLP-3530
[#346](https://github.com/eclipse-tractusx/portal-backend/pull/346)
=> feat(seeding): add configuration values

.github/workflows/kics.yml
exclude docs directory from kics scan
example in docs folder leads to false positive, example run:
https://github.com/eclipse-tractusx/portal-iam/actions/runs/6958476672
=> chore(kics): exclude docs directory from scan

CHANGELOG.md, charts/centralidp/values.yaml, charts/sharedidp/values.yaml, consortia/argocd-app-templates/centralidp/appsetup-templateconsortia.yaml, consortia/argocd-app-templates/centralidp/appsetup-templategeneric.yaml, consortia/argocd-app-templates/sharedidp/appsetup-templateconsortia.yaml, consortia/argocd-app-templates/sharedidp/appsetup-templategeneric.yaml, consortia/environments/centralidp/values-templateconsortia.yaml, consortia/environments/centralidp/values-templategeneric.yaml, consortia/environments/sharedidp/values-templateconsortia.yaml, consortia/environments/sharedidp/values-templategeneric.yaml, import/realm-config/consortia/catenax-central/beta/CX-Central-realm.json, import/realm-config/consortia/catenax-central/dev/CX-Central-realm.json, import/realm-config/consortia/catenax-central/int/CX-Central-realm.json, import/realm-config/consortia/catenax-central/pen/CX-Central-realm.json, import/realm-config/consortia/catenax-central/rc/CX-Central-realm.json, import/realm-config/consortia/catenax-central/stable/CX-Central-realm.json, import/realm-config/generic/catenax-central/CX-Central-realm.json
- remove view_wallet from Dataspace Discovery
- assign Identity Wallet Management to technical user which previously had Connector User assigned
assignment of view_wallet to the role "Dataspace Discovery" was wrong
https://github.com/eclipse-tractusx/portal-iam/pull/37
CPLP-3556
=> fix(init-realm): change role assignment

CHANGELOG.md, charts/centralidp/README.md, charts/centralidp/README.md.gotmpl, charts/sharedidp/README.md, charts/sharedidp/README.md.gotmpl, docs/technical documentation/11. FAQ.md, docs/technical documentation/12. Upgrade Details.md
- add upgrade approach
- update changelog
- update FAQ for CX-Central config
=> docs(release): update docs for v2.0.0

NOTICE.md
change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131
=> chore(trg-2.04): change portal-cd references to portal

charts/centralidp/README.md.gotmpl, charts/centralidp/values.yaml, charts/sharedidp/README.md.gotmpl, charts/sharedidp/values.yaml
- change to major tag for image to get latest minor updates
- set version label to major version
- use debian-11 image tag to remove collation version mismatch warning at upgrade
- docs: update upgrade info
follow up to https://github.com/eclipse-tractusx/portal-iam/pull/63
#62
=> chore(upgrade-v23): improve database dependency

.github/dependabot.yml, .github/pull_request_template.md, .gitignore, CONTRIBUTING.md, charts/centralidp/values.yaml, docs/technical documentation/14. How to contribute.md
- chore(centralidp-seeding): set resource limits and increase requests
- docs: add contribution details
- chore: add dependabot.yml file
- chore(gitignore): add local values file
#54
eclipse-tractusx/portal#219
=> chore: set resource limits for seeding and docs

.github/workflows/centralidp-chart-test.yaml, .github/workflows/chart-release.yaml, .github/workflows/cx-iam-consortia.yml, .github/workflows/cx-iam.yml, .github/workflows/kics.yml, .github/workflows/pullRequest-lint.yaml, .github/workflows/sharedidp-chart-test.yaml, .github/workflows/trivy.yml
upgrade gh actions and change to pinned actions full length commit sha
https://github.com/eclipse-tractusx/portal/issues/225
=> chore(gh-actions): upgrade and change to pinned commit sha

import/realm-config/consortia/catenax-central/beta/CX-Central-realm.json, import/realm-config/consortia/catenax-central/dev/CX-Central-realm.json, import/realm-config/consortia/catenax-central/int/CX-Central-realm.json, import/realm-config/consortia/catenax-central/pen/CX-Central-realm.json, import/realm-config/consortia/catenax-central/rc/CX-Central-realm.json, import/realm-config/consortia/catenax-central/stable/CX-Central-realm.json
remove Cl9-CDQ-Fraud client from user role mappings in CX-Central consortia data.
Forgot role mapping when removing client.
Keycloak server doesn't start up.
https://github.com/eclipse-tractusx/portal-iam/issues/66
=> fix(consortia): remove obsolete client from user role mappings

import/keycloak-themes/catenax-shared/login/resources/js/Main.js
Remove check not equal to username in password update
In the updated keycloak base form the username is not visible any more and we have no value to check for.
https://github.com/eclipse-tractusx/portal-iam/issues/100
=> fix(theme): remove password username check

import/keycloak-themes/catenax-shared-portal/login/resources/js/Main.js
Fix password update theme for portal
After Keycloak major version upgrade the custom theme was broken because the hidden username has been removed.
#100 
=> fix(theme): fix password update for portal

import/realm-config/generic/catenax-central/CX-Central-realm.json
- fix cx-central realm configuration: 
- #146
- #136
- #143
- #151
- fix name of default role to enable import of realm via seeding job, without proper naming of the default role the seeding job runs into error eclipse-tractusx/portal-backend#800 (comment), to prepare for upgrade of seeding job
https://github.com/eclipse-tractusx/portal/issues/379
=> chore(3.0.1): update cx-central realm config

import/keycloak-themes/catenax-central/login/resources/js/Main.js
- Update central search field regex validation code to allow special characters and umlauts
Companies that contained special characters or umlauts were not searchable via the search field. 
#164
=> fix: update regex to allow special and umlaut characters

docs/technical documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
Add the role: `view_idp` to the `Business Admin` role
The business admin has to many rights
Refs: #178
=> chore: add view_idp to business admin

import/realm-config/generic/catenax-central/CX-Central-realm.json
Add `subscribe_service` to Business Admin composite role. As defined by [permission matrix](https://github.com/eclipse-tractusx/portal-assets/blob/v2.1.0/public/assets/images/content/PortalRoleAndPermissionMatrix.png).
This missing permission prevented Business Admin from subscribing to services.
Refs: eclipse-tractusx/portal-iam#172
=> feat(roles): add subscribe_service permission to Business Admin

docs/technical documentation/03. Clients.md, docs/technical documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
This pull request adjusts the Central-IDP realm configuration to be more align with the BPDM default authentication configuration for the release 24.08. / BPDM version 6.1.0 as described [here](https://github.com/eclipse-tractusx/bpdm/blob/release/6.1.x/docs/arc42/arc42-bpdm.md#authentication--autorization)
- add Orchestrator client and permissions
- add Orchestrator roles
- add service accounts for Gate, Pool and Cleaning Service Dummy
- fixes some roles and permissions for the BPDM clients
All changes were tested with BPDM to setup the golden record process successfully.
Currently, the configuration between the Central-IDP and BPDM is not completely aligned. This leads to more complexity and configuration overhead for operators. Also, currently Central-IDP is missing some technical …
=> feat: add BPDM authentication configuration for 24.08. release

docs/technical documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
Adjust the create notification role to be specific for its use case
The create_notifications role was to generic and is only used for the ssi related notifications
Refs: [#812](https://github.com/eclipse-tractusx/portal-backend/issues/812)
https://github.com/eclipse-tractusx/portal-backend/pull/906
https://github.com/eclipse-tractusx/ssi-credential-issuer/pull/233
=> feat(notification): adjust create notification role

CHANGELOG.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
New `technical_roles_management` composite role with name `Registration Internal` with:
- `invite_new_partner`
- `view_submitted_applications`
Both were previously only available for CX Admin.
Backend change: eclipse-tractusx/portal-backend#1002
Operator company wants to integrate 3rd party service to send out invites. Allows inviting and reviewing status via API.
Refs: eclipse-tractusx/portal-backend#932
=> feat(tech user): add new operator invite tech user

docs/technical documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
onboarding service provider:
- remove create role
- assign configure role to cx admin
- update docs
https://github.com/eclipse-tractusx/portal-iam/issues/186
=> feat(osp): remove create role and assign configure role to cx admin

charts/centralidp/templates/job-seeding.yaml, charts/sharedidp/templates/job-seeding.yaml
add securityContext to initContainers
https://github.com/eclipse-tractusx/portal-iam/issues/86
=> chore(seeding): add securityContext to initContainers

charts/centralidp/values.yaml
increase memory for realm seeding
observed OOM kill when testing seeding of extra service accounts
#86
=> chore(centralidp): increase memory for realm seeding

.github/workflows/trivy.yml
add "newer" options according to [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04)
workflow continuously runs into error: "Path does not exist: trivy-results2.sarif"
https://github.com/eclipse-tractusx/portal/issues/467
=> chore(trivy): add options according to TRG 8.04

charts/centralidp/values.yaml, charts/sharedidp/values.yaml
increase memory for realm seeding job
install on int env showed OOM kills
#86
=> fix: increase memory for realm seeding job

docs/admin/technical-documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json, import/realm-config/generic/catenax-shared/master-realm.json
BEGIN_COMMIT_OVERRIDE
fix(cx-central centralidp): enable user profiles to address user attributes change coming from version upgrade
fix(master sharedidp): update realm to not require user profiles, discovered as part of https://github.com/eclipse-tractusx/portal-backend/pull/1154
fix(cx-central centralidp): add technical_roles_management role from Cl2-CX-Portal client to client scope of sa-cl2-05
fix(cx-central centralidp): add create_ssi_notifications role  from Cl2-CX-Portal client to sa-cl24-01
fix(docs): add store_didDocument role to technical user accounts
END_COMMIT_OVERRIDE
https://github.com/eclipse-tractusx/portal-iam/issues/226 --> [change to user profiles](https://www.keycloak.org/docs/latest/release_notes/index.html#changes-to-the-user-representation-in-both-admin-api-and-acco …
=> fix(e2e-test findings): adjust realm config

charts/centralidp/Chart.yaml, charts/centralidp/README.md, charts/sharedidp/Chart.yaml, charts/sharedidp/README.md
release 4.0.0-rc.3
https://github.com/eclipse-tractusx/portal/issues/482
=> build(4.0.0-rc.3): bump chart version

docs/admin/technical-documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
* Added `Connector Management` composite role in the cx-central realm in the central idp
As portal user, I want to create `Connector Management` technical user, so that I can access connector registration features without using UI.
#271 
=> feat(cx-central realm): Add Connector Management composite role in the central idp

docs/admin/technical-documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
Assigned the view_subscription role to Offer Management
In order to allow all users to have access to endpoints that requires view_subscriptions role. i.e: /api/Apps/provided/subscription-status.
On the documentation [06. Roles & Rights Concept.md](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/admin/technical-documentation/06.%20Roles%20%26%20Rights%20Concept.md), this role is presented on the description:
["Offer Management" Technical User Cannot Access Subscription Status Endpoint](https://github.com/eclipse-tractusx/portal-iam/issues/278)
=> fix: assign view_subscription role to Offer Management

charts/centralidp/values.yaml, docs/admin/technical-documentation/03. Clients.md, environments/helm-values/centralidp/values-int.yaml, import/realm-config/generic/catenax-central/CX-Central-realm.json
One additional service account for regional clearing house to access update of onboarding step after calling /validation endpoint. 
- name: sa-cl2-06
- clientRoles: 
- Cl2-CX-Portal
- update_application_checklist_value
Testing regional clearing house functionality and providing initial 2nd client for operator with multiple clearing houses.
eclipse-tractusx/portal-iam#282
=> feat(centralidp): add service account for regional clearing house

docs/admin/technical-documentation/06. Roles & Rights Concept.md, import/realm-config/generic/catenax-central/CX-Central-realm.json
Assigned the view_app_subscription role to Offer Management
In order to allow all users to have access to endpoints that requires view_app_subscription role. i.e: /api/Apps/provided/subscription-status.
On the documentation [06. Roles & Rights Concept.md](https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/admin/technical-documentation/06.%20Roles%20%26%20Rights%20Concept.md), this role is presented on the description:
["Offer Management" Technical User Cannot Access Subscription Status Endpoint](https://github.com/eclipse-tractusx/portal-iam/issues/280)
=> fix: add missing view_app_subscripton role to offer management role composite

charts/centralidp/Chart.yaml
Fix chart version for centralidp 4.2.0-rc.1
Release candidate for 25.06.
https://github.com/eclipse-tractusx/portal/issues/541
=> build(4.2.0-rc.1): fix centralidp bump version
