eclipse-tractusx/portal-iam

- .github/workflows/cx-iam-consortia.yml
change pattern of tag to trigger workflow for  consortia init containers 
to enable testing between releases
n/a
> chore(workflow): change tag pattern for trigger

- import/keycloak-themes/catenax-central/login/resources/css/Main.css
- import/keycloak-themes/catenax-shared-portal/login/resources/css/Main.css
- import/keycloak-themes/catenax-shared/login/resources/css/Main.css
set correct copyright header
https://github.com/eclipse-tractusx/portal-iam/issues/15
> fix: set correct copyright header

- SECURITY.md
update security.md
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file
> docs: update security.md

- charts/sharedidp/templates/secret-sharedidp-realms.yaml
- consortia/argocd-app-templates/centralidp/appsetup-templateconsortia.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-templateconsortia.yaml
- consortia/environments/centralidp/values-templateconsortia.yaml
- consortia/environments/sharedidp/values-beta.yaml
- consortia/environments/sharedidp/values-dev.yaml
- consortia/environments/sharedidp/values-int.yaml
- consortia/environments/sharedidp/values-pen.yaml
- consortia/environments/sharedidp/values-rc.yaml
- consortia/environments/sharedidp/values-stable.yaml
- consortia/environments/sharedidp/values-templateconsortia.yaml
- import/realm-config/consortia/catenax-central/beta/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/dev/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/int/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/pen/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/rc/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/stable/CX-Central-realm.json
- import/realm-config/consortia/catenax-shared/beta/Onboarding-Provider-realm.json
- import/realm-config/consortia/catenax-shared/dev/Onboarding-Provider-realm.json
- import/realm-config/consortia/catenax-shared/int/Onboarding-Provider-realm.json
- import/realm-config/consortia/catenax-shared/pen/Onboarding-Provider-realm.json
- import/realm-config/consortia/catenax-shared/rc/Onboarding-Provider-realm.json
- import/realm-config/consortia/catenax-shared/stable/Onboarding-Provider-realm.json
Add the onboarding-provider realm
add a user for the newly added realm
To be able to test the newest network to network features from the product-portal
N/A - Jira Issue: CPLP-3145
> feat(n2n): add realm and user for onboarding provider

- consortia/argocd-app-templates/centralidp/appsetup-templategeneric.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-templategeneric.yaml
- consortia/environments/centralidp/values-templategeneric.yaml
- consortia/environments/sharedidp/values-templategeneric.yaml
fix: change init setup for generic template
added wrong init container
Link to Github issue.
> fix(consortia): change init setup for generic template

- CHANGELOG.md
- import/realm-config/consortia/catenax-central/beta/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/dev/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/int/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/pen/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/rc/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/stable/CX-Central-realm.json
- import/realm-config/generic/catenax-central/CX-Central-realm.json
update realm config
add findings from e2e testing
https://github.com/eclipse-tractusx/portal-iam/issues/47
> chore(v2.1.0): update realm config

- charts/centralidp/templates/_helpers.tpl
- charts/centralidp/templates/job-seeding.yaml
- charts/centralidp/values.yaml
- fix function tpl for nameOverride and fullnameOverride
- enable unique resource name for iam seeding job
- change to imagePullPolicy IfNotPresent
improve seeding job for upgrade
#47
> chore(upgrade): change seeding for cx-central realm

- CHANGELOG.md
- charts/centralidp/values.yaml
- charts/sharedidp/values.yaml
- consortia/argocd-app-templates/centralidp/appsetup-stable.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-stable.yaml
- consortia/environments/centralidp/values-beta.yaml
- consortia/environments/centralidp/values-dev.yaml
- consortia/environments/centralidp/values-int.yaml
- consortia/environments/centralidp/values-pen.yaml
- consortia/environments/centralidp/values-rc.yaml
- consortia/environments/centralidp/values-templateconsortia.yaml
- consortia/environments/centralidp/values-templategeneric.yaml
- consortia/environments/sharedidp/values-beta.yaml
- consortia/environments/sharedidp/values-dev.yaml
- consortia/environments/sharedidp/values-int.yaml
- consortia/environments/sharedidp/values-pen.yaml
- consortia/environments/sharedidp/values-rc.yaml
- consortia/environments/sharedidp/values-templateconsortia.yaml
- consortia/environments/sharedidp/values-templategeneric.yaml
add container registry to images
may lead to dns resolution issues for instance when using podman in default setup
#47
> chore: add container registry to images

- import/realm-config/consortia/catenax-central/beta/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/dev/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/int/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/pen/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/rc/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/stable/CX-Central-realm.json
remove obsolete bpdm management in CX-Central consortia data.
clean up
https://github.com/eclipse-tractusx/portal-iam/issues/66
> chore(consortia): remove obsolete bpdm management

- docs/technical documentation/12. Upgrade Details.md
Please review @evegufy
Version update query missed a comma and did not run
> docs: add missing comma in update query

- .github/workflows/centralidp-chart-test.yaml
- .github/workflows/sharedidp-chart-test.yaml
- CHANGELOG.md
- README.md
- charts/centralidp/README.md
- charts/centralidp/README.md.gotmpl
- docs/technical documentation/16. Known-Knowns.md
- import/realm-config/consortia/catenax-central/beta/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/dev/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/int/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/pen/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/rc/CX-Central-realm.json
- import/realm-config/consortia/catenax-central/stable/CX-Central-realm.json
- import/realm-config/generic/catenax-central/CX-Central-realm.json
- update cx-central realm config
- update changelog
- update post-upgrade configuration
- docs: add known known section
- helm-test: change helm install command
#102
> chore: update cx-central realm config

- charts/centralidp/Chart.yaml
- charts/centralidp/README.md
- charts/centralidp/values.yaml
- charts/sharedidp/Chart.yaml
- charts/sharedidp/README.md
- charts/sharedidp/values.yaml
- consortia/argocd-app-templates/centralidp/appsetup-beta.yaml
- consortia/argocd-app-templates/centralidp/appsetup-int.yaml
- consortia/argocd-app-templates/centralidp/appsetup-pen.yaml
- consortia/argocd-app-templates/centralidp/appsetup-rc.yaml
- consortia/argocd-app-templates/centralidp/appsetup-stable.yaml
- consortia/argocd-app-templates/centralidp/appsetup-templateconsortia.yaml
- consortia/argocd-app-templates/centralidp/appsetup-templategeneric.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-beta.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-int.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-pen.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-rc.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-stable.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-templateconsortia.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-templategeneric.yaml
- consortia/environments/centralidp/values-beta.yaml
- consortia/environments/centralidp/values-int.yaml
- consortia/environments/centralidp/values-pen.yaml
- consortia/environments/centralidp/values-templateconsortia.yaml
- consortia/environments/centralidp/values-templategeneric.yaml
- consortia/environments/sharedidp/values-beta.yaml
- consortia/environments/sharedidp/values-int.yaml
- consortia/environments/sharedidp/values-pen.yaml
- consortia/environments/sharedidp/values-templateconsortia.yaml
- consortia/environments/sharedidp/values-templategeneric.yaml
finalize version 3.0.0 by merge into main
https://github.com/eclipse-tractusx/sig-release/issues/671
> build(3.0.0): release version

- .github/dependabot.yml
dependabot: group version updates pull request
eclipse-tractusx/portal#300
> chore(dependabot): group version updates

- consortia/argocd-app-templates/centralidp/appsetup-dev.yaml
- consortia/argocd-app-templates/centralidp/appsetup-int.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-dev.yaml
- consortia/argocd-app-templates/sharedidp/appsetup-int.yaml
argocd templates: update namespace for dev and int
https://github.com/eclipse-tractusx/portal/issues/337
> chore(consortia): update namespace for dev and int

- docs/technical documentation/03. Clients.md
add table with seeded clients and service accounts
https://github.com/eclipse-tractusx/portal-assets/issues/335
> docs: add table with seeded clients and service accounts

- charts/centralidp/README.md.gotmpl
- import/realm-config/generic/catenax-central/CX-Central-realm.json
- rename default-role also for newly added sa-cl7-cx-7
- add information at upgrade
Follow up to https://github.com/eclipse-tractusx/portal-iam/pull/157
https://github.com/eclipse-tractusx/portal/issues/379
> chore: follow up to default role renaming

- CHANGELOG.md
- charts/centralidp/Chart.yaml
- charts/centralidp/README.md
- charts/centralidp/README.md.gotmpl
- charts/centralidp/values.yaml
- charts/sharedidp/Chart.yaml
- charts/sharedidp/README.md
- charts/sharedidp/README.md.gotmpl
- charts/sharedidp/values.yaml
finalize version 3.0.1 by merge into main
https://github.com/eclipse-tractusx/portal/issues/349
> build(3.0.1): bump version and update docs

- docs/technical documentation/01. Introduction.md
- docs/technical documentation/02. Generic Setup.md
- docs/technical documentation/03. Clients.md
- docs/technical documentation/04 User Management.md
- docs/technical documentation/05. Authentication Configuration.md
- docs/technical documentation/06. Roles & Rights Concept.md
- docs/technical documentation/07. Password Policy.md
- docs/technical documentation/08. Email Configuration.md
- docs/technical documentation/09. Event Logging.md
- docs/technical documentation/10. Generic Security.md
- docs/technical documentation/13. Operational Notes.md
Adjusted the documentation files  in regards of 
- spelling errors removed 
- phrasing partly adjusted for an easier understanding
- adjusted markdown
Adjustments should help the user to read and understand the documentation more easily. 
#181 
> docs: Improved Documentation

- docs/consultation/consultation.md
remove reference to pull request from other Github org
will be a dead link soon as the org is supposed to be deleted
https://github.com/eclipse-tractusx/portal-iam/issues/184
> docs: remove reference to pull request from other Github org

- .github/workflows/release-please.yml
- CHANGELOG.md
- docs/technical documentation/14. How to contribute.md
- docs/technical documentation/17. Dev Flow.md
- docs/technical documentation/18. Release Process.md
add release please action, prepare changelog for 4.0.0-alpha.1 and docs for dev and release process
simplify release process
> chore: add release please workflow and docs

- environments/argocd-app-templates/centralidp/appsetup-int.yaml
- environments/argocd-app-templates/centralidp/appsetup-stable.yaml
- environments/argocd-app-templates/sharedidp/appsetup-int.yaml
- environments/argocd-app-templates/sharedidp/appsetup-stable.yaml
- environments/helm-values/centralidp/values-stable.yaml
- environments/helm-values/sharedidp/values-stable.yaml
This PR introduces configurations for the stable environment adapted to the main branch.
relates to https://github.com/eclipse-tractusx/portal/issues/408
> build: add configuration for stable environment

- environments/helm-values/centralidp/values-int.yaml
- environments/helm-values/centralidp/values-stable.yaml
- environments/helm-values/sharedidp/values-int.yaml
- environments/helm-values/sharedidp/values-stable.yaml
update deployment configuration
- remove deprecated proxy parameter
- set production mode to false for testing
Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.
https://github.com/eclipse-tractusx/portal/issues/465
> chore(envs): update deployment configuration

- CHANGELOG.md
- charts/centralidp/Chart.yaml
- charts/centralidp/README.md
- charts/centralidp/values.yaml
- charts/sharedidp/Chart.yaml
- charts/sharedidp/README.md
- charts/sharedidp/values.yaml
- environments/argocd-app-templates/centralidp/appsetup-int.yaml
- environments/argocd-app-templates/centralidp/appsetup-stable.yaml
- environments/argocd-app-templates/sharedidp/appsetup-int.yaml
- environments/argocd-app-templates/sharedidp/appsetup-stable.yaml
Merge the latest changes to the main branch
To have the latest changes available in the main branch
https://github.com/eclipse-tractusx/portal/issues/482
> build(4.0.0-rc.2): bump version and update docs

- charts/centralidp/values.yaml
- charts/sharedidp/values.yaml
fix image tag for realm seeding job
https://github.com/eclipse-tractusx/portal/issues/482
> chore(4.0.0): fix image tag for realm seeding job

- docs/admin/technical-documentation/06. Roles & Rights Concept.md
- import/realm-config/generic/catenax-central/CX-Central-realm.json
change role assignments to composite roles from the portal client and update rights and roles concept
Role assignments didn't match documentation in  r&r concept
https://github.com/eclipse-tractusx/portal-iam/issues/185
> fix(cx-central realm): change role assignments and update r&r concept

- CHANGELOG.md
- charts/centralidp/Chart.yaml
- charts/centralidp/README.md
- charts/sharedidp/Chart.yaml
- charts/sharedidp/README.md
- environments/argocd-app-templates/centralidp/appsetup-int.yaml
- environments/argocd-app-templates/centralidp/appsetup-stable.yaml
- environments/argocd-app-templates/sharedidp/appsetup-int.yaml
- environments/argocd-app-templates/sharedidp/appsetup-stable.yaml
- Bump RC version.
- Create new rc release.
Refs: #301
> build(4.2.1-rc.2): bump version and update docs
